[package]
name = "turbofish-aquarium"
version = "0.1.1"
edition = "2021"
authors = ["nsfisis"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
termion = "4.0.3"
